version: '3.8'
services:
  db:
    image: 'mysql'
    container_name: mysql-container
    volumes:
      # Where our data will be persisted
      # Add :z to avoid SELinux problems
      # Without a label, the security system might prevent the processes running inside the container from using the content.
      - ./db:/var/lib/mysql:z
      - ./files:/var/lib/mysql-files:z
    restart: 'always'
    expose:
      # Opens port 3306 on the container
      - '3306'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
#    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: 'cerber'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
# Names our volume
volumes:
  mydb:
