version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cerber
    ports:
      - "2345:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
