version: '3.8'
services:
  postgres:
    image: postgres:16
    # for vacuuming only
    shm_size: 1g
    restart: always
    # make static ip
    networks:
      postgres-network:
        ipv4_address: 10.5.0.2
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cerber
    # to not share posrt for outside
#    ports:
#      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./files:/tmp/files

networks:
  postgres-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1