version: '3.8'
services:
  issb-mysql:
    image: 'mysql:5.7'
    volumes:
      # Where our data will be persisted
      - /home/berzerk/docker/bases/issb:/var/lib/mysql
      #- /home/berzerk:/home
    restart: 'always'
    networks:
      - issb-network
    expose:
      # Opens port 3306 on the container
      - '3306'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'cerber'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'romul'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Q1234567890@'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
networks:
  issb-network:
    driver: bridge